--------------------------------------------------------
-- Archivo creado  - domingo-mayo-05-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLE_COMPRA
--------------------------------------------------------

  CREATE TABLE "DETALLE_COMPRA" 
   (	"ID_DETALLE_PEDIDO" VARCHAR2(4 BYTE), 
	"ID_PEDIDO" VARCHAR2(4 BYTE), 
	"ID_PRODUCTO" VARCHAR2(1000 BYTE), 
	"PRECIO_TOTAL" NUMBER, 
	"NOMBRE_EMPLEADO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_TRANSACCION
--------------------------------------------------------

  CREATE TABLE "DETALLE_TRANSACCION" 
   (	"ID_TRANSACCION" NUMBER, 
	"ID_PRODUCTO" VARCHAR2(1000 BYTE), 
	"ID_CLIENTE" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO_UNITARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTRO_CLIENTES
--------------------------------------------------------

  CREATE TABLE "REGISTRO_CLIENTES" 
   (	"ID_CLIENTE" NUMBER, 
	"NOMBRE_COMPLETO" VARCHAR2(100 BYTE), 
	"CONTRASEÑA" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTRO_EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "REGISTRO_EMPLEADOS" 
   (	"ID_EMPLEADO" NUMBER, 
	"NOMBRE_COMPLETO" VARCHAR2(50 BYTE), 
	"CARGO" VARCHAR2(50 BYTE), 
	"CORREO" VARCHAR2(70 BYTE), 
	"CONTRASEÑA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TABLA_PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "TABLA_PRODUCTOS" 
   (	"ID_PRODUCTO" VARCHAR2(4 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER, 
	"PROOVEDOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACCIONES
--------------------------------------------------------

  CREATE TABLE "TRANSACCIONES" 
   (	"ID_TRANSACCION" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"FECHA_COMPRA" DATE, 
	"COMPRA_TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DETALLE_COMPRA
SET DEFINE OFF;
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B089','C015','A006  A009  A014','5000','NICOLAS STEVEN ANAYA RAMIREZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B090','C016','A002  A003  A007  A010  A018  A020','2000','JEISON ALEXANDER CORTES TAFUR');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B091','C017','A001  A003  A007  A016  A019','4000','BRAYAN ANDRES VARGAS HERNANDEZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B092','C018','A012  A018','15000','CLAUDIA SORAYA NOVOA SANCHEZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B093','C019','A007  A019','2000','LAURA PAOLA ORTIZ TUMAY');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B094','C020','A013','3000','NICOLAS STEVEN ANAYA RAMIREZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B095','C021','A001  A005  A010  A011  A020','25000','JEISON ALEXANDER CORTES TAFUR');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B096','C022','A002  A007  A015  A017  A018','8000','BRAYAN ANDRES VARGAS HERNANDEZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B097','C023','A014','25000','CLAUDIA SORAYA NOVOA SANCHEZ');
Insert into DETALLE_COMPRA (ID_DETALLE_PEDIDO,ID_PEDIDO,ID_PRODUCTO,PRECIO_TOTAL,NOMBRE_EMPLEADO) values ('B098','C024','A007  A010  A016','30000','LAURA PAOLA ORTIZ TUMAY');
REM INSERTING into DETALLE_TRANSACCION
SET DEFINE OFF;
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10025','A006  A009  A014','5784123','3','188000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10026','A002  A003  A007  A010  A018  A020','1010057890','6','35000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10027','A001  A003  A007  A016  A019','80472300','5','102000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10028','A012  A018','1112874503','2','27000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10029','A007  A019','1000612478','2','45000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10030','A013','2236547','1','60000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10031','A001  A005  A010  A011  A020','1001543002','5','28000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10032','A002  A007  A015  A017  A018','96547810','5','46000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10033','A014','1103024756','1','150000');
Insert into DETALLE_TRANSACCION (ID_TRANSACCION,ID_PRODUCTO,ID_CLIENTE,CANTIDAD,PRECIO_UNITARIO) values ('10034','A007  A010  A016','1130248752','3','70000');
REM INSERTING into REGISTRO_CLIENTES
SET DEFINE OFF;
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('5784123','ERIKA HOYOS','ERIK45');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1010057890','JUAN PABLO MARTINEZ','JPM369');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('80472300','SANTIAGO FLOREZ','FLOR,?');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1112874503','DEIMER PEREZ','KOKE14');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1000612478','JULIET HERRERA','KEHELI00,');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('2236547','ESTEBAN QUINTERO','12345EQ');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1001543002','PRICILA GOEZ','GOL_87');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('96547810','JULIAN GAVIRIA','GAVILI20');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1103024756','PAOLA ORTIZ','JI_KOOK99');
Insert into REGISTRO_CLIENTES (ID_CLIENTE,NOMBRE_COMPLETO,"CONTRASEÑA") values ('1130248752','JAFET MEJIA','VALEZKA21');
REM INSERTING into REGISTRO_EMPLEADOS
SET DEFINE OFF;
Insert into REGISTRO_EMPLEADOS (ID_EMPLEADO,NOMBRE_COMPLETO,CARGO,CORREO,"CONTRASEÑA") values ('1012564780','NICOLAS STEVEN ANAYA RAMIREZ','ADMINISTRADOR','NICOLAS.ANAYAR@CUN.EDU.CO','NICO_80');
Insert into REGISTRO_EMPLEADOS (ID_EMPLEADO,NOMBRE_COMPLETO,CARGO,CORREO,"CONTRASEÑA") values ('1003541009','JEISON ALEXANDER CORTES TAFUR','ADMINISTRADOR','JEISON.CORTES@CUN.EDU.CO','ALEXCOR.009');
Insert into REGISTRO_EMPLEADOS (ID_EMPLEADO,NOMBRE_COMPLETO,CARGO,CORREO,"CONTRASEÑA") values ('1100478996','BRAYAN ANDRES VARGAS HERNANDEZ','ADMINISTRADOR','BRAYAN.VARGASHHE@CUN.EDU.CO','BRAVAR$8996');
Insert into REGISTRO_EMPLEADOS (ID_EMPLEADO,NOMBRE_COMPLETO,CARGO,CORREO,"CONTRASEÑA") values ('1000524789','CLAUDIA SORAYA NOVOA SANCHEZ','ADMINISTRADOR','CLAUDIA.NOVOAS@CUN.EDU.CO','CLAUNOVOA90');
Insert into REGISTRO_EMPLEADOS (ID_EMPLEADO,NOMBRE_COMPLETO,CARGO,CORREO,"CONTRASEÑA") values ('1010639874','LAURA PAOLA ORTIZ TUMAY','ADMINISTRADOR','LAURA.ORTIZT@CUN.EDU.CO','ROCCO99');
REM INSERTING into TABLA_PRODUCTOS
SET DEFINE OFF;
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A001','MANZANAS','FRUTA','4000','FRUTEO');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A002','ZANAHORIA','VERDURA','2000','FRUTEO');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A003','ESPINACAS','VERDURA','3000','FRUTEO');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A004','BANANO','FRUTA','3000','FRUTEO');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A005','POLLO','CARNE','8000','VIANDCOL');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A006','SALMON','PESCADO','30000','VIANDCOL');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A007','TERNERA','CERNE','15000','VIANDCOL');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A008','CAMARONES','PESCADO','25000','VIANDCOL');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A009','CHAMPU','ASEO','8000','KIPCLIN');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A010','PASTA DE DIENTES','ASEO','5000','KIPCLIN');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A011','JABON DE MANOS','ASEO','3000','KIPCLIN');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A012','PAPEL HIGIENICO','ASEO','25000','KIPCLIN');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A013','VINO TINTO CABERNET SAUVIGNON','LICORES','60000','BAVARIA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A014','WHISKY ESCOCES','LICORES','150000','BAVARIA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A015','CERVEZA CORONA','LICORES','25000','BAVARIA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A016','VODKA','LICORES','50000','BAVARIA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A017','ARROZ','DESPENSA','2000','SUDESPENSA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A018','PASTA','DESPENSA','2000','SUDESPENSA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A019','ACEITE DE OLIVIA','DESPENSA','30000','SUDESPENSA');
Insert into TABLA_PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,CATEGORIA,PRECIO,PROOVEDOR) values ('A020','FROOT LOOPS','DESPENSA','8000','SUDESPENSA');
REM INSERTING into TRANSACCIONES
SET DEFINE OFF;
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10025','5784123',to_date('01/05/24','DD/MM/RR'),'188000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10026','1010057890',to_date('17/04/24','DD/MM/RR'),'35000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10027','80472300',to_date('15/04/24','DD/MM/RR'),'102000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10028','1112874503',to_date('03/05/24','DD/MM/RR'),'27000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10029','1000612478',to_date('27/03/24','DD/MM/RR'),'45000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10030','2236547',to_date('31/03/24','DD/MM/RR'),'60000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10031','1001543002',to_date('07/04/24','DD/MM/RR'),'28000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10032','96547810',to_date('19/04/24','DD/MM/RR'),'46000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10033','1103024756',to_date('13/04/24','DD/MM/RR'),'150000');
Insert into TRANSACCIONES (ID_TRANSACCION,ID_CLIENTE,FECHA_COMPRA,COMPRA_TOTAL) values ('10034','1130248752',to_date('15/05/24','DD/MM/RR'),'70000');
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENTES_PK" ON "REGISTRO_CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_COMPRA_PK" ON "DETALLE_COMPRA" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_TRANSACCION_PK" ON "DETALLE_TRANSACCION" ("ID_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLEADOS_PK" ON "REGISTRO_EMPLEADOS" ("NOMBRE_COMPLETO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLA_PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLA_PRODUCTOS_PK" ON "TABLA_PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACCIONES_PK" ON "TRANSACCIONES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_COMPRA_PK" ON "DETALLE_COMPRA" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_TRANSACCION_PK" ON "DETALLE_TRANSACCION" ("ID_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENTES_PK" ON "REGISTRO_CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLEADOS_PK" ON "REGISTRO_EMPLEADOS" ("NOMBRE_COMPLETO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLA_PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLA_PRODUCTOS_PK" ON "TABLA_PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACCIONES_PK" ON "TRANSACCIONES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
